---
# Define hosting environment
hosting_infrastructure: aws

# Define AWS region. Comment out the one you DO NOT wish to use with #
aws_region: "eu-west-3"
#aws_region: "us-west-1"

# Define environment name
env_id: "launchSplunkInfra"

# DNS domain
dns_domain: "{{ env_id }}.com"

# Define the AWS default image
# this is the redhat Enterprise Linux HVM in Paris region (eu-west-3)
aws_image: ami-0ba7c4110ca9bfe0b

# Set the SSH keypair with EC2 Instances
aws_key_name: "ansible_master_kp"

# Availability zone of resources
aws_zone: "eu-west-3a"
#aws_zone: "us-east-1b"
#aws_zone: "us-east-1c"


# Second AZ if multi-AZ is needed during cloudformation deployment
#aws_zone2: "us-east-1a"
aws_zone2: "eu-west-3b"
#aws_zone2: "us-east-1c"
