---
#Override default image
#aws_image: "{{ aws_image}}"

#   Cloud Formation Stack Name
stack_name: "stacksplunkV0"

# SSH Keypair for the instance
aws_key_name: "ansible_master_kp"

#Establish server hostname
server_name: "sh01.galaxy.splunk.infra.com"
server_name2: "sh02.galaxy.splunk.infra.com"
server_name3: "sh03.galaxy.splunk.infra.com"
server_name4: "dmc.galaxy.splunk.infra.com"
server_name5: "idx01.galaxy.splunk.infra.com"
server_name6: "hfwd01.galaxy.splunk.infra.com"

#Type of AWS instance
aws_instancetype: "t2.medium"

#Establish  server subnets
subnet: subnet-801972cd #eu-west-3c
subnet2: subnet-e60e289d #eu-west-3b

# Establish EBS Encryption key
# NOT USED
ebs_key: "ff01e1f8-edfa-44d6-b511-3fc07445765c"


# Establish private Route53 DNS zone
private_hosted_zone: Z060707325L428YTZUUHI

# Establish VPC
vpc_id: vpc-c454b5ac

#Disks to attach to instance
disks:
  - name: "root_volume"
    type: "gp2"
    size: "12"
    device_name: "/dev/sda1"