AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to deploy multiple servers in aws"

Parameters:
  Image:
    Description: "EC2 ami to be used"
    Type: "AWS::EC2::Image::Id"
  KeyPairName:
    Description: "SSH Key to asign to the EC2 instances"
    Type: "AWS::EC2::KeyPair::KeyName"
  InstanceType:
    Default: "t3.medium"
    Description: "The instance type to be used"
    Type: "String"
  EnvId:
    Description: "Environment ID tag to use"
    Type: "String"
  RootVolumeName:
    Description: "Device name of the root volume"
    Type: "String"
  RootVolumeType:
    Description: "Device type of the root volume"
    Type: "String"
  RootVolumeSize:
    Description: "Device size of the root volume"
    Type: "String"
  ServerDomain:
    Description: "Domain of the server"
    Type: "String"
  ServerName:
    Description: "Full name of the server"
    Type: "String"
  ServerName2:
    Description: "Full name of the server"
    Type: "String"
  ServerName3:
    Description: "Full name of the server"
    Type: "String"
  ServerName4:
    Description: "Full name of the server"
    Type: "String"
  ServerName5:
    Description: "Full name of the server"
    Type: "String"
  ServerName6:
    Description: "Full name of the server"
    Type: "String"
  AwsZone:
    Description: "AWS Availability Zone to deploy to"
    Type: "AWS::EC2::AvailabilityZone::Name"
  AwsZone2:
    Description: "AWS Availability Zone to deploy to"
    Type: "AWS::EC2::AvailabilityZone::Name"
  #EBSkey:
    #Description: "Key used to encrypt EBS volumes"
    #Type: "String"
  Subnet:
    Description: "Subnet instance will reside in"
    Type: "AWS::EC2::Subnet::Id"
  Subnet2:
    Description: "Subnet instance will reside in"
    Type: "AWS::EC2::Subnet::Id"
  PrivateRoute53HostedZone:
    Description: "Route53 hosted zone for private DNS"
    Type: "AWS::Route53::HostedZone::Id"
  VPC:
    Description: "VPC of resource"
    Type: "AWS::EC2::VPC::Id"
  
Resources:
#Creation of Search Heads
  sh01:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone 
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize
  sh02:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName2
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone 
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize
  sh03:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName3
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone2 
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet2
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize
#dmcserver
  dmc:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName4
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet2
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize
#Creation of Indexers
  idx01:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName5
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet2
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize
#Heavy Forwarders
  hfwd01:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref Image
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: !Ref ServerName6
        - Key: 'env_id'
          Value: !Ref EnvId
      AvailabilityZone: !Ref AwsZone2
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet: 
            - sg-03c71033aa765ba2b
          SubnetId: !Ref Subnet2
      BlockDeviceMappings:
        - DeviceName: !Ref RootVolumeName
          Ebs:
            VolumeType: !Ref RootVolumeType 
            DeleteOnTermination: "true"
            VolumeSize: !Ref RootVolumeSize

  sh01PrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for sh01
      Name: !Ref ServerName
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt sh01.PrivateIp

  sh02PrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for sh02
      Name: !Ref ServerName2
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt sh02.PrivateIp

  sh03PrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for sh03
      Name: !Ref ServerName3
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt sh03.PrivateIp
  
  dmcPrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for dmc
      Name: !Ref ServerName4
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt dmc.PrivateIp

  idx01PrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for idx01
      Name: !Ref ServerName5
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt idx01.PrivateIp

  hfwd01PrivateDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PrivateRoute53HostedZone
      Comment: Private DNS entry for hfwd01
      Name: !Ref ServerName6
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt hfwd01.PrivateIp